development:
  email:    tapas@neu.edu
  api_key:  tapas12345
  password: tapas12345
staging: 
  email: tapas@neu.edu 
  api_key: <%= ENV["STAGING_TAPAS_API_KEY"] %>
  password: <%= ENV["STAGING_TAPAS_PASSWORD"] %>