development:
  email:    tapas@neu.edu
  api_key:  tapas12345
  password: tapas12345
staging:
  email: tapas@neu.edu
  api_key: <%= ENV["PRODUCTION_TAPAS_API_KEY"] %>
  password: <%= ENV["PRODUCTION_TAPAS_PASSWORD"] %>
production:
  email: tapas@neu.edu
  api_key: <%= ENV["PRODUCTION_TAPAS_API_KEY"] %>
  password: <%= ENV["PRODUCTION_TAPAS_PASSWORD"] %>
